"""empty message

Revision ID: b40fdb5e2798
Revises: acc08b97673b
Create Date: 2021-03-02 10:18:21.943641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40fdb5e2798'
down_revision = 'acc08b97673b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_answer_user_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_answer_user_id_question', 'question', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
